apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        test: "123"
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456789"
        - name: MYSQL_DATABASE
          value: "ecommerce_db"
        volumeMounts:
          - name: mysql-storage # Tên phải khớp với "volumes" bên dưới
            mountPath: /var/lib/mysql # Thư mục data *bên trong* container
      volumes:
      - name: mysql-storage # Đặt tên cho volume
        persistentVolumeClaim:
            claimName: mysql-pvc # Tên phải khớp với file PVC đã tạo