# 3-hdfs-namenode-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-namenode-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-hdfs-nn # Phải khớp với PV
  resources:
    requests:
      storage: 2Gi # Phải khớp với PV