# 8-hdfs-datanode-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-datanode-deployment
spec:
  replicas: 1 # Bạn có thể tăng số này lên nếu muốn
  selector:
    matchLabels:
      app: hdfs-datanode
  template:
    metadata:
      labels:
        app: hdfs-datanode
    spec:
      containers:
      - name: hdfs-datanode
        image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
        env:
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://hdfs-namenode-svc:8020
        volumeMounts:
        - name: hdfs-storage
          mountPath: /hadoop/dfs/data
      volumes:
      - name: hdfs-storage
        persistentVolumeClaim:
          claimName: hdfs-datanode-pvc # Yêu cầu PVC của DataNode